import React, { useEffect } from 'react';

import styled, { createGlobalStyle } from 'styled-components';
import axios from 'axios';

import { useAppContext } from '../context/AppContext';
import { useRouter } from 'next/router';

import Head from 'next/head';
import Search from '../components/Search/Search';
import CardGrid from '../components/CardGrid/CardGrid';
import Modal from '../components/Modal/Modal';
import DetailCardList from '../components/DetailCardList/DetailCardList';

const GlobalStyle = createGlobalStyle`
	body {
		background-color: #DCDCDC;
	}
`;

const MainContainer = styled.div`
  height: calc(100vh - 80px);
  margin-top: 80px;
  width: 100vw;
`;

const Home = () => {
  const { state, setState } = useAppContext();

  const router = useRouter();
  const { search = '' } = router.query;

  const getRandomCharacter = (gridDataList) => {
    return gridDataList[Math.floor(Math.random() * gridDataList.length)] || {};
  };

  useEffect(() => {
    const randomCharacter = () => {
      let characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
      return characters[Math.floor(Math.random() * characters.length)];
    };

    return axios
      .get(
        `https://gateway.marvel.com:443/v1/public/characters?limit=100&nameStartsWith=${randomCharacter()}&ts=1&apikey=6c915ef1dcee8a56cc163a02592aad2d&hash=a85ef61e3494356c56e955d2ac0974f0`
      )
      .then((res) => {
        const results = res?.data?.data?.results || [];
        const character = getRandomCharacter(results);
        return axios
          .get(
            `https://gateway.marvel.com:443/v1/public/characters/${1009610}/comics?issueNumber=22&limit=100&ts=1&apikey=6c915ef1dcee8a56cc163a02592aad2d&hash=a85ef61e3494356c56e955d2ac0974f0`
          )
          .then((res) => {
            const comicList = res?.data?.data?.results || [];
            setState({
              ...state,
              gridData: [character, ...comicList],
              heroComics: comicList
            });
          });
      });
  }, []);

  const setFavComics = (id) => {
    console.log('clg comicsStars', state?.comicsStars);
    let favs = [...(state?.comicsStars || [])];
    const idIndex = favs?.indexOf(id);
    if (idIndex === -1) {
      favs.push(id);
    } else {
      favs.splice(idIndex, 1);
    }
    return setState({ ...state, comicsStars: favs });
  };

  return (
    <MainContainer>
      <Head>
        <title>Marvel Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Search />
      <pre style={{ maxWidth: '100vw', overflow: 'auto' }}>
        {JSON.stringify(state)}
      </pre>
      {state?.gridData?.length ? (
        <CardGrid
          onClick={() => setState({ ...state, showModal: true })}
          heroes={state.gridData}
          hasBanner={!search}
        />
      ) : (
        <p>Hero not found, try again</p>
      )}
      {state.showModal && (
        <Modal
          title={state?.gridData?.[0]?.name}
          onCloseClick={() => setState({ ...state, showModal: false })}
        >
          <DetailCardList
            favs={state.comicsStars}
            data={state.heroComics}
            onCardClick={(id) => alert(`Redirige a comic ${id}`)}
            onStarClick={(id) => setFavComics(id)}
          />
        </Modal>
      )}
    </MainContainer>
  );
};

export default Home;
